apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-project
  namespace: argocd
spec:
  description: Projet GitOps de demo pour apprendre Argo CD sur l'environnement prod
  sourceRepos:
    - https://github.com/RobinThiriet/ArgoCD.git
  destinations:
    - namespace: demo-prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
