apiVersion: v1
kind: Secret
metadata:
  name: guacamole-secrets
type: Opaque
stringData:
  POSTGRES_DB: guacamole_staging
  POSTGRES_USER: guacamole_staging
  POSTGRES_PASSWORD: CHANGE_ME_GUACAMOLE_STAGING_DB_PASSWORD
