apiVersion: v1
kind: Secret
metadata:
  name: guacamole-secrets
type: Opaque
stringData:
  POSTGRES_DB: guacamole_db
  POSTGRES_USER: guacamole_user
  POSTGRES_PASSWORD: CHANGE_ME_GUACAMOLE_DB_PASSWORD
