apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guacamole-prod

resources:
  - ../../base

commonLabels:
  app.kubernetes.io/environment: prod

patches:
  - path: ingress-patch.yaml
  - path: secret-patch.yaml
  - path: storage-patch.yaml
  - path: guacamole-scale-patch.yaml
  - path: guacd-scale-patch.yaml
