apiVersion: v1
kind: Secret
metadata:
  name: guacamole-secrets
type: Opaque
stringData:
  POSTGRES_DB: guacamole_prod
  POSTGRES_USER: guacamole_prod
  POSTGRES_PASSWORD: CHANGE_ME_GUACAMOLE_PROD_DB_PASSWORD
