apiVersion: v1
kind: Secret
metadata:
  name: guacamole-secrets
type: Opaque
stringData:
  POSTGRES_DB: guacamole_dev
  POSTGRES_USER: guacamole_dev
  POSTGRES_PASSWORD: CHANGE_ME_GUACAMOLE_DEV_DB_PASSWORD
